### ISSUE TITLE
Cannot install using npm install @types/tone

### ISSUE THREAD

**Issue by oli-ver** [Tonejs/TypeScript#5] opened 2017-09-22 19:02 UTC
npm install @types/tone --save

leads to:

npm ERR! code E404
npm ERR! 404 Not Found: @types/tone@latest

Am I doing something wrong?

**Comment by tambien** [comment] 2017-09-23 19:46
I haven't published this to @types because many of the definitions are currently out of date. I am seeking contributors to help maintain. Happily accepting PRs!

**Comment by tekool** [comment] 2018-01-20 16:32
For those wanting to use it in its state anyway, you can install it with: `npm install -D git+https://github.com/Tonejs/TypeScript.git`

**Comment by jcapinc** [comment] 2019-09-03 03:43
I am using this library, so far all the types seem to work well, if I see any mis-matches between the documentation/functionality and the types I will document here and work out a pr. 

If I finish working with it and I don't find any issues than it might be ready for prime time.

**Comment by jacobclarke92** [comment] 2019-09-03 04:15
That likely isn't going to happen because the new version of Tone will be written from the ground up in Typescript, making this repo effectively redundant https://github.com/Tonejs/Tone.js/wiki/Typescripting-Tone.js

These types only officially support tone@^0.12.80

**Comment by tambien** [comment] 2019-09-04 00:25
duplicate of #2, so going to close

**Closed as completed by tambien** 2019-09-04 00:25 UTC
